version: "3.8"

services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=enceladus
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./docker/volumes/postgresql:/var/lib/postgresql
      - ./data/init-dev.sql:/docker-entrypoint-initdb.d/init.sql
