version: "3.8"

services:
  api:
    build: ./
    environment:
      - PORT=5000
      - JWT_SECRET=secret
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=enceladus
      - POSTGRES_HOST=postgres
    ports:
      - 5000:5000
    depends_on:
      - postgres
    networks:
      - network
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=enceladus
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./docker/volumes/postgresql:/var/lib/postgresql
      - ./data/init-dev.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - network

networks:
  network:
    driver: bridge
